### ISSUE TITLE
Caching an API without ETag and Expires header

### ISSUE THREAD

**Issue by mingca** [flexirest/flexirest#113]
### Expected behaviour

API returns header without Expire and Etag and Flexirest does not cache it even though I put `Flexirest::Base.perform_caching = true` and configured Rails app to use redis_store cache.

### Desired behaviour

It should cache the response although Etag and Flexirest are not present when it's explicitly defined to cache the result.

**Comment by andyjeffries** [comment]
Sorry, this is against designed behaviour. For example, how long should it cache this result for, indefinitely? What happens if the remote API changes its data, how would you know to refresh it?

That's why we rely on the Expire and Etag headers, they come from the server, so the API provider determines cache characteristics for all clients.

If you want to override this, and make a per-request (or global) decision that you know better than the API provider and want to cache it, there's an example of this at https://github.com/flexirest/flexirest/blob/master/docs/using-callbacks.md (search for `cache_all_people`).

**Comment by mingca** [comment]
Thanks, @andyjeffries. Could you plz tell me how to manually expire previous responses? I'd like to do this on update request.

**Comment by andyjeffries** [comment]
By default it uses `Rails.cache` as the cache store (but you can override that).

The keys are in the format of `ClassName:URL`; for example `Person:/v1/people`

So you should just be able to make the key in the same format (you can tail the logs in debug mode to be sure of the key used) and then use `Rails.cache.delete("Person:/v1/people")` to clear the cache.
