### ISSUE TITLE
Support base_url with variables or some other way to scope set of resources with variables

### ISSUE THREAD

**Issue by htcarr3** [flexirest/flexirest#163]
### Explanation
I am building an api integration/mapping to a service which scopes almost all routes by a namespace, which is essentially a project-id.  
I've tried reading through the docs on how best to handle this (*without writing "/namespaces/:namespace" on every class). Let me know if you know of some hook I might be missing which would allow me to Dry this up a bit. Thank you!

### Expected behaviour

```ruby

class API < Flexirest::Base
  base_url "https://example.com/namespaces/:namespace"
  get :all, "/apis"
  get :find "/apis/:id"
end

API.all(namespace: "default")

# => ERRORin  `handle_response': The GET to '/api/v1/namespaces/:namespace/apis?namespace=default' returned a 404 status 
```
### Desired behaviour

GET to '/api/v1/namespaces/default/apis

**Comment by andyjeffries** [comment]
Hey @htcarr3 , the good news is there is a way of handling this. 

First off, I tried to add a quick feature where they would be automatically parsed in, but that's not as simple as it would seem (due to a pooled connection manager on the base URL).

However, you can handle this with [callbacks](https://github.com/flexirest/flexirest/blob/master/docs/using-callbacks.md)

```ruby
class MyBaseClass < Flexirest::Base
  before_request do |name, request|
    request.url.gsub!(":namespace", request.post_params.delete(:namespace) || request.get_params.delete(:namespace))
  end
end


    class ParameterBaseURLExampleClient < ExampleClient
      base_url "http://www.example.com/:namespace"


      get :user, "/users/:id"
    end
```

**Comment by htcarr3** [comment]
Ah yes thank you! Instead of even this so the base url, I'll simply add some validation in that before_request hook. Something like this will work great.

```ruby
  class NamespacedResource < Resource # Resource inherits from Flexirest::Base
    before_request do |_name, request|
      namespace = request.post_params.delete(:namespace) ||
                  request.get_params.delete(:namespace) ||
                  FireFly.config.default_namespace

      raise ArgumentError, 'Namespace is required' unless namespace

      request.url.prepend("/namespaces/#{namespace}")
    end
  end
```

**Comment by htcarr3** [comment]
Is it possible to define more than one before_request hook?

**Comment by andyjeffries** [comment]
Absolutely, the documentation page I linked to shows an example of multiple `before_request` calls (including using a symbol or a direct block)

**Comment by htcarr3** [comment]
Yes, though the order is that it calls the callbacks on parents first correct?

**Comment by andyjeffries** [comment]
Honest answer is I don't know (can't remember) but I think it's in the order defined in a class, but parent class will precede the current class. If you find the answer, feel free to submit a PR to https://github.com/flexirest/flexirest/blob/master/docs/using-callbacks.md stating it ;-)

**Comment by htcarr3** [comment]
I think that is roughly correct. In general are there any particular corners of this library you are looking for support on? I'm surprised at the lack of tools in Ruby land on API/REST ORMs.

**Comment by andyjeffries** [comment]
Not really anything specific, anything you can do though is appreciated - any new features, or documentation improvement, or whatever...

To give some background - I wrote it because I was fed up with reinventing the wheels at every new job I had, it's had minimal work in the past few years because it's reached the point where mostly "it just works". That's not to say there's no polish to be added, but it's got to the point where it's pretty much good (so no glaring areas of "I wish it did X" or "this is bit is rubbish").

But anything you can see/do, greatly appreciated.

**Comment by htcarr3** [comment]
Well, I appreciate the work you have put into it and can say that I feel similarly about writing api resource object modeling libraries. rom-http might be more of an ideal framework for me (I generally like using tools in and around the dry-rb ecosystem), but at this moment it's enforcement of strict schema makes it -- essentially -- not useable
