### ISSUE TITLE
{before,after}_request not triggered for faked response?

### ISSUE THREAD

**Issue by execjosh** [flexirest/flexirest#45]
I don't think the `{before,after}_request`s are triggered for faked responses.  Is this correct?  I expected that they would be triggered..

Here's my isolated test case.

```ruby
require 'flexirest'

class Foo < Flexirest::Base
  before_request do |name, req|
    puts "before request #{name}"
  end

  after_request do |name, res|
    puts "after request #{name}"
  end

  get :all, '/foo/:bar', fake: -> (req) {
    [{id: 1, yadda: 'yadda'}]
  }
end

Foo.all(bar: 1).each do |foo|
  p foo
end
```

_Actual_

```
#<Foo id: 1, yadda: "yadda">
```

_Expected_

```
before request :all
#<Foo id: 1, yadda: "yadda">
after request :all
```

**Comment by andyjeffries** [comment]
You're absolutely right, they aren't - and this is intentional/by design. It may help for me to explain some of this background thinking...

**Callbacks**

The callbacks were originally implemented to deal with two specific situations - an API that required non-standard authentication/encryptions and APIs that returned either less than ideal response formats/in the process of changing.

**Fake responses**

Fake responses were designed for situations where the API had been specified but didn't exist as yet, maybe another team or company were developing it.  The API coming back would be in a perfect format, because it was still being built.

So, that's the logic behind the two sets of functionality.  Now I think about it, I can see a case where the API isn't yet developed but is being done so in a less than ideal final format (even when it is finished).  However, I would argue that the `fake` response should be as the API call would complete and then any `after_request` callback has mangled it.

However, I'd be interested in hearing more about your use case - maybe you have a very good reason for them to be triggered - and I'd consider changing it (or at least with a config option to keep it backwards compatible).

**Comment by execjosh** [comment]
Thank you for the explanation.

My problem seems to be that I have misinterpreted how the faked responses were used.  Without having delved into the code, I just assumed that everything about the request would run as normal, except that it would not actually go out on the network—the value of the faked response would be used.

As to my use case, I want to format the parameters injected into the URL (e.g., `:id`).  The path is like `/foo/:yyyy/:mm/:dd`.  However, the replacing code just `to_s`s the value, which leads the month and day parts to be non-padded when under ten.

Obviously, this formatting could be done by the caller; but, that's not DRY.

I wanted to see what I could do with the `before_request` without having to use a test suite, local server, etc. and found that they are not triggered.  Is there a better way to introduce formatting for the param replacing?

**Comment by andyjeffries** [comment]
What I don't understand is that a faked request won't hit any server, so what happens to URL parameters is irrelevant. So this is just for your debugging of the before_request. In which case I would use a http://mockbin.org/ endpoint to test it, it's only during development (if you're not using a test suite anyway).

**Comment by execjosh** [comment]
Going back to the issue as titled, I understand the design decisions.

For what I was attempting to one-off test, `fake` is not intended for and does not work as I assumed.

Thank you for taking the time to work on this project!  I'll close this issue as it is resolved 😄
