### ISSUE TITLE
Error Exception handler

### ISSUE THREAD

**Issue by mkhairi** [flexirest/flexirest#68]
is there a away to rescue from exception in flexirest class?
 eg: 

```ruby
class Bank < Flexirest::Base
   get  :find, "/banks/:id" do
      begin
        #passthrough
      rescue Flexirest::HTTPClientException, Flexirest::HTTPServerException => e
        Rails.logger.error("API returned #{e.status} : #{e.result.message}")
        render "{\"error\":1234}"
      end
   end
end

# no luck
```

**Comment by andyjeffries** [comment]
No, it's not intended to be used inside the class. I'd accept a PR so that it did work if you wanted to do it. But I'll close this issue for now as it's not really a bug nor a feature request that I'm likely to work on (I'm not trying to be rude; but I do have a limited amount of hours and no other requests for this feature)
