### ISSUE TITLE
Not works with devise

### ISSUE THREAD

**Issue by casecamp** [flexirest/flexirest#77]
If I include flexirest with user model which devise gem in it , it throws the following error

``<class:User>': undefined method `devise' for User:Class (NoMethodError)`

**Comment by andyjeffries** [comment]
Can you give a complete code sample that reproduces the problem?

**Comment by casecamp** [comment]
```
class User < < Flexirest::Base
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable,  :confirmable
end
```

**Comment by andyjeffries** [comment]
Ahhh OK, so instead of a conflict, what you're actually seeing is that Devise isn't integrated with Flexirest. This is correct. It integrates with ActiveRecord out of the box, but if you want to use it with something else, then you have to do a little more integration work yourself.

Here's a link you may find useful, but either way this is a Devise issue not a Flexirest one.

http://4trabes.com/2012/10/31/remote-authentication-with-devise/
