### ISSUE TITLE
Problem updating a model

### ISSUE THREAD

**Issue by heldopslippers** [flexirest/flexirest#83]
When updating a model. It seems like it doesn't assign the given attributes on time: 
Given I have a hash like this: 
`{"user"=>{"id"=>"11", "first_name"=>"jaa", "last_name"=>"te Wies", "email"=>"test@me.com", "company_name"=>""}`

And update it as follows:
`
@current_user.update(user_params)
`

It doesn't assign the given atttributes, but uses the old. 
When I do the following, it works: 
`
@current_user.update(user_params)
@current_user.update(user_params)
`

So it seems, that the patch on the model already fires when it still has to assign the attributes. 

Doing: 
`User.update(user_params)`
Works as expected though.

**Comment by andyjeffries** [comment]
I've just tested this using RequestBin and it seems to work fine for me:

```ruby
class User < Flexirest::Base
  base_url "https://requestb.in"

  post :find, "", fake: {"id"=>"11", "first_name"=>"jaa", "last_name"=>"te Wies", "email"=>"test@me.com", "company_name"=>""}
  post :update, "/1eabgcg1"
end

@current_user = User.find
@current_user.update(first_name: "John", last_name: "Smith")
```

The requestbin (https://requestb.in/1eabgcg1?inspect) received:

```
company_name:
email: test@me.com
last_name: Smith
id: 11
first_name: John
```

So the old `id`, `company_name` and `email` and the new `first_name` and `last_name`. I can't see what the problem is, could you create a small reproducible test case?
